import { ServiceDetail } from "@/components/services/ServiceDetailDrawer";

export const POPULAR_SERVICES_LIST: ServiceDetail[] = [
  {
    id: "pan-application-protean",
    name: "PAN Application",
    category: "Identity",
    authority: "Income Tax Department / Protean",
    officialApplicationUrl: "https://onlineservices.proteantech.in/paam/endUserRegisterContact.html",
    officialInformationUrl: "https://onlineservices.proteantech.in/paam/endUserRegisterContact.html",
    officialDomain: "onlineservices.proteantech.in",
    officialDomains: ["onlineservices.proteantech.in", "incometax.gov.in"],
    urlType: "DIRECT_APPLICATION",
    supportLevel: "BROWSER_ASSISTANCE",
    description:
      "Apply for a new Permanent Account Number (PAN) Form 49A for Indian citizens through Protean eGov Technologies (formerly NSDL).",
    requirements: [
      "Proof of Identity (Aadhaar Card, Passport, Voter ID)",
      "Proof of Address (Utility bill, Aadhaar, Domicile)",
      "Proof of Date of Birth (10th Marksheet, Birth Certificate)",
      "Recent passport-size photograph (3.5 x 2.5 cm)",
      "Applicant signature on plain white paper",
    ],
  },
  {
    id: "income-certificate",
    name: "Income Certificate",
    category: "Revenue & Social Welfare",
    authority: "Revenue Department / State e-District (ServicePlus)",
    officialApplicationUrl: "https://serviceonline.gov.in/",
    officialInformationUrl: "https://serviceonline.gov.in/",
    officialDomain: "serviceonline.gov.in",
    officialDomains: ["serviceonline.gov.in", "edistrict.delhigovt.nic.in"],
    urlType: "OFFICIAL_ENTRY",
    supportLevel: "BROWSER_ASSISTANCE",
    description:
      "Official certificate issued by the State Revenue Department stating annual household income for fee reimbursement and welfare schemes.",
    requirements: [
      "Salary slips / Form 16 or Income Affidavit",
      "Aadhaar Card of applicant and household head",
      "Ration Card or BPL Card copy",
      "Self-declaration certificate",
    ],
  },
  {
    id: "caste-certificate",
    name: "Caste Certificate",
    category: "Revenue & Social Welfare",
    authority: "Revenue & Backward Classes Welfare Department",
    officialApplicationUrl: "https://serviceonline.gov.in/",
    officialInformationUrl: "https://serviceonline.gov.in/",
    officialDomain: "serviceonline.gov.in",
    officialDomains: ["serviceonline.gov.in"],
    urlType: "OFFICIAL_ENTRY",
    supportLevel: "BROWSER_ASSISTANCE",
    description:
      "Statutory certificate certifying Scheduled Caste (SC), Scheduled Tribe (ST), or Other Backward Classes (OBC/SEBC) community status.",
    requirements: [
      "Aadhaar Card of applicant",
      "Family member's existing caste certificate or genealogy proof",
      "School Leaving Certificate (TC) mentioning community",
      "Domicile or Residence Certificate",
    ],
  },
  {
    id: "scholarship-nsp",
    name: "Scholarship",
    category: "Higher Education & Welfare",
    authority: "National Scholarship Portal (NSP) / MoE",
    officialApplicationUrl: "https://scholarships.gov.in/",
    officialInformationUrl: "https://scholarships.gov.in/",
    officialDomain: "scholarships.gov.in",
    officialDomains: ["scholarships.gov.in"],
    urlType: "DIRECT_APPLICATION",
    supportLevel: "FULL_ASSIST",
    description:
      "Central and State government scholarship schemes for post-matric and pre-matric students across India via DBT Direct Benefit Transfer.",
    requirements: [
      "One-Time Registration (OTR) / Aadhaar",
      "Current Academic Year Bonafide Certificate",
      "Previous year marks memo / grade card",
      "Income Certificate valid for current FY",
      "Active bank account seeded with Aadhaar (NPCI mapper)",
    ],
  },
  {
    id: "voter-services",
    name: "Voter Services",
    category: "Electoral Services",
    authority: "Election Commission of India (ECI)",
    officialApplicationUrl: "https://voters.eci.gov.in/",
    officialInformationUrl: "https://voters.eci.gov.in/",
    officialDomain: "voters.eci.gov.in",
    officialDomains: ["voters.eci.gov.in", "eci.gov.in"],
    urlType: "OFFICIAL_ENTRY",
    supportLevel: "GUIDED",
    description:
      "Form 6 application for registration of new voter / elector and EPIC digital card download.",
    requirements: [
      "Passport size color photograph",
      "Proof of Age (Aadhaar / PAN / Birth Certificate)",
      "Proof of Ordinary Residence (Electricity bill, Aadhaar, Rent deed)",
    ],
  },
  {
    id: "passport-seva",
    name: "Passport",
    category: "External Affairs",
    authority: "Consular, Passport & Visa Division (MEA)",
    officialApplicationUrl: "https://services1.passportindia.gov.in/",
    officialInformationUrl: "https://www.passportindia.gov.in/",
    officialDomain: "passportindia.gov.in",
    officialDomains: ["passportindia.gov.in", "services1.passportindia.gov.in"],
    urlType: "DIRECT_APPLICATION",
    supportLevel: "GUIDED",
    description:
      "Ordinary Passport application Form for fresh issuance or re-issue under the Passport Seva system.",
    requirements: [
      "Proof of Present Address",
      "Proof of Date of Birth",
      "Non-ECR document (Matriculation Certificate / Higher degree)",
    ],
  },
  {
    id: "driving-licence",
    name: "Driving Licence",
    category: "Transport",
    authority: "Ministry of Road Transport & Highways (Sarathi)",
    officialApplicationUrl: "https://sarathi.parivahan.gov.in/",
    officialInformationUrl: "https://sarathi.parivahan.gov.in/",
    officialDomain: "sarathi.parivahan.gov.in",
    officialDomains: ["sarathi.parivahan.gov.in", "parivahan.gov.in"],
    urlType: "OFFICIAL_ENTRY",
    supportLevel: "GUIDED",
    description:
      "Learner's Licence (LL) and Permanent Driving Licence (DL) online application and slot booking on Sarathi Parivahan.",
    requirements: [
      "Aadhaar authentication",
      "Age proof document",
      "Address proof document",
      "Medical Fitness Certificate (Form 1 / 1A if required)",
    ],
  },
];
